line_length: 
  - 500 # warning
  - 600 # Error
disabled_rules:
  - trailing_whitespace
  - implicit_getter
  - cyclomatic_complexity
  - function_body_length
  - discouraged_direct_init
excluded:
  - Pods
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly